rm -Rfv debug
rm -Rfv release
rm -v quake3.ncb
rm -v quake3.opt
rm -v quake3.plg
rm -v quake3.stt
rm -Rfv cgame\debug  
rm -Rfv cgame\release  
rm -v cgame\cgame.ncb
rm -v cgame\cgame.opt
rm -v cgame\cgame.plg
rm -v cgame\cgame.stt
rm -Rfv game\debug  
rm -Rfv game\release  
rm -v game\game.ncb
rm -v game\game.opt
rm -v game\game.plg
rm -v game\game.stt
rm -Rfv ui\debug  
rm -Rfv ui\release  
rm -v ui\ui.ncb
rm -v ui\ui.opt
rm -v ui\ui.plg
rm -v ui\ui.stt
rm -Rfv renderer\debug  
rm -Rfv renderer\release  
rm -v renderer\renderer.ncb
rm -v renderer\renderer.opt
rm -v renderer\renderer.plg
rm -v renderer\renderer.stt
rm -Rfv botlib\debug  
rm -Rfv botlib\release  
rm -v botlib\botlib.ncb
rm -v botlib\botlib.opt
rm -v botlib\botlib.plg
rm -v botlib\botlib.stt
rm -Rfv botlai\debug  
rm -Rfv botlai\release  
rm -v botai\botai.dsp
rm -v botai\botai.plg
rm -Rfv bspc\debug  
rm -Rfv bspc\release  
rm -v bspc\bspc.exe
rm -v bspc\bspc.log
rm -v bspc\bspc.ncb
rm -v bspc\bspc.opt
rm -v bspc\bspc.pdb
rm -v bspc\bspc.plg
rm -Rfv unix\debugi386-glibc  
rm -Rfv unix\releasei386-glibc  
rm -Rfv "mac\MacQuake3 Data"  
rm -Rfv macosx\Client\Q3Test.app  
rm -Rfv macosx\Client\Q3Test.build  
